services:
  mysql:
    image: mysql:8.0.36
    networks:
      - sentrip-net
    environment:
      MYSQL_ROOT_PASSWORD: 11032003
      MYSQL_DATABASE: DASENTRIP
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    networks:
      - sentrip-net
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker

networks:
  sentrip-net:
    driver: bridge
